/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_lang_CIL */

#ifndef _Included_ikvm_lang_CIL
#define _Included_ikvm_lang_CIL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_byte
 * Signature: (Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_ikvm_lang_CIL_unbox_1byte
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_boolean
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ikvm_lang_CIL_unbox_1boolean
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_short
 * Signature: (Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_ikvm_lang_CIL_unbox_1short
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_char
 * Signature: (Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_ikvm_lang_CIL_unbox_1char
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_int
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ikvm_lang_CIL_unbox_1int
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_float
 * Signature: (Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_ikvm_lang_CIL_unbox_1float
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_long
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ikvm_lang_CIL_unbox_1long
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_double
 * Signature: (Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_ikvm_lang_CIL_unbox_1double
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_byte
 * Signature: (B)Lcli/System/Byte;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1byte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_boolean
 * Signature: (Z)Lcli/System/Boolean;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1boolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_short
 * Signature: (S)Lcli/System/Int16;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1short
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_char
 * Signature: (C)Lcli/System/Char;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1char
  (JNIEnv *, jclass, jchar);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_int
 * Signature: (I)Lcli/System/Int32;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1int
  (JNIEnv *, jclass, jint);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_float
 * Signature: (F)Lcli/System/Single;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1float
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_long
 * Signature: (J)Lcli/System/Int64;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1long
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_double
 * Signature: (D)Lcli/System/Double;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1double
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_sbyte
 * Signature: (B)Lcli/System/SByte;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1sbyte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_ushort
 * Signature: (S)Lcli/System/UInt16;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1ushort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_uint
 * Signature: (I)Lcli/System/UInt32;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1uint
  (JNIEnv *, jclass, jint);

/*
 * Class:     ikvm_lang_CIL
 * Method:    box_ulong
 * Signature: (J)Lcli/System/UInt64;
 */
JNIEXPORT jobject JNICALL Java_ikvm_lang_CIL_box_1ulong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_sbyte
 * Signature: (Lcli/System/SByte;)B
 */
JNIEXPORT jbyte JNICALL Java_ikvm_lang_CIL_unbox_1sbyte
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_ushort
 * Signature: (Lcli/System/UInt16;)S
 */
JNIEXPORT jshort JNICALL Java_ikvm_lang_CIL_unbox_1ushort
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_uint
 * Signature: (Lcli/System/UInt32;)I
 */
JNIEXPORT jint JNICALL Java_ikvm_lang_CIL_unbox_1uint
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_lang_CIL
 * Method:    unbox_ulong
 * Signature: (Lcli/System/UInt64;)J
 */
JNIEXPORT jlong JNICALL Java_ikvm_lang_CIL_unbox_1ulong
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
