/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_AssemblyClassLoader */

#ifndef _Included_ikvm_runtime_AssemblyClassLoader
#define _Included_ikvm_runtime_AssemblyClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    setWrapper
 * Signature: (Lcli/System/Reflection/Assembly;)V
 */
JNIEXPORT void JNICALL Java_ikvm_runtime_AssemblyClassLoader_setWrapper
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    loadClass
 * Signature: (Ljava/lang/String;Z)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_AssemblyClassLoader_loadClass
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    getResource
 * Signature: (Ljava/lang/String;)Ljava/net/URL;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AssemblyClassLoader_getResource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    getResources
 * Signature: (Ljava/lang/String;)Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AssemblyClassLoader_getResources
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    findResource
 * Signature: (Ljava/lang/String;)Ljava/net/URL;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AssemblyClassLoader_findResource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    findResources
 * Signature: (Ljava/lang/String;)Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AssemblyClassLoader_findResources
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    lazyDefinePackages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ikvm_runtime_AssemblyClassLoader_lazyDefinePackages
  (JNIEnv *, jobject);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ikvm_runtime_AssemblyClassLoader_toString
  (JNIEnv *, jobject);

/*
 * Class:     ikvm_runtime_AssemblyClassLoader
 * Method:    getAssemblyClassLoader
 * Signature: (Lcli/System/Reflection/Assembly;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AssemblyClassLoader_getAssemblyClassLoader
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
