/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Thread */

#ifndef _Included_java_lang_Thread
#define _Included_java_lang_Thread
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Thread_MIN_PRIORITY
#define java_lang_Thread_MIN_PRIORITY 1L
#undef java_lang_Thread_NORM_PRIORITY
#define java_lang_Thread_NORM_PRIORITY 5L
#undef java_lang_Thread_MAX_PRIORITY
#define java_lang_Thread_MAX_PRIORITY 10L
/*
 * Class:     java_lang_Thread
 * Method:    getMainThreadGroup
 * Signature: ()Ljava/lang/ThreadGroup;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Thread_getMainThreadGroup
  (JNIEnv *, jclass);

/*
 * Class:     java_lang_Thread
 * Method:    casContextClassLoader
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/ClassLoader;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_Thread_casContextClassLoader
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     java_lang_Thread
 * Method:    isCCLOverridden
 * Signature: (Ljava/lang/Thread;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_Thread_isCCLOverridden
  (JNIEnv *, jclass, jobject);

/*
 * Class:     java_lang_Thread
 * Method:    dumpThreads
 * Signature: ([Ljava/lang/Thread;)[[Ljava/lang/StackTraceElement;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_Thread_dumpThreads
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     java_lang_Thread
 * Method:    getThreads
 * Signature: ()[Ljava/lang/Thread;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_Thread_getThreads
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
