/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Class_Atomic */

#ifndef _Included_java_lang_Class_Atomic
#define _Included_java_lang_Class_Atomic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Class_Atomic
 * Method:    casReflectionData
 * Signature: (Ljava/lang/Class;Ljava/lang/ref/SoftReference;Ljava/lang/ref/SoftReference;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_Class_00024Atomic_casReflectionData
  (JNIEnv *, jclass, jclass, jobject, jobject);

/*
 * Class:     java_lang_Class_Atomic
 * Method:    casAnnotationType
 * Signature: (Ljava/lang/Class;Lsun/reflect/annotation/AnnotationType;Lsun/reflect/annotation/AnnotationType;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_Class_00024Atomic_casAnnotationType
  (JNIEnv *, jclass, jclass, jobject, jobject);

/*
 * Class:     java_lang_Class_Atomic
 * Method:    casAnnotationData
 * Signature: (Ljava/lang/Class;Ljava/lang/Class/AnnotationData;Ljava/lang/Class/AnnotationData;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_Class_00024Atomic_casAnnotationData
  (JNIEnv *, jclass, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
