/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_ref_Reference */

#ifndef _Included_java_lang_ref_Reference
#define _Included_java_lang_ref_Reference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_ref_Reference
 * Method:    noclassgc
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_ref_Reference_noclassgc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
