/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_jar_JarFile */

#ifndef _Included_java_util_jar_JarFile
#define _Included_java_util_jar_JarFile
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_jar_JarFile_OPEN_READ
#define java_util_jar_JarFile_OPEN_READ 1L
#undef java_util_jar_JarFile_OPEN_DELETE
#define java_util_jar_JarFile_OPEN_DELETE 4L
#undef java_util_jar_JarFile_ENDNRD
#define java_util_jar_JarFile_ENDNRD 4L
/*
 * Class:     java_util_jar_JarFile
 * Method:    getMetaInfEntryNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_java_util_jar_JarFile_getMetaInfEntryNames
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
