/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_Bits */

#ifndef _Included_java_nio_Bits
#define _Included_java_nio_Bits
#ifdef __cplusplus
extern "C" {
#endif
#undef java_nio_Bits_MAX_SLEEPS
#define java_nio_Bits_MAX_SLEEPS 9L
#undef java_nio_Bits_JNI_COPY_TO_ARRAY_THRESHOLD
#define java_nio_Bits_JNI_COPY_TO_ARRAY_THRESHOLD 6L
#undef java_nio_Bits_JNI_COPY_FROM_ARRAY_THRESHOLD
#define java_nio_Bits_JNI_COPY_FROM_ARRAY_THRESHOLD 6L
#undef java_nio_Bits_UNSAFE_COPY_THRESHOLD
#define java_nio_Bits_UNSAFE_COPY_THRESHOLD 1048576LL
/*
 * Class:     java_nio_Bits
 * Method:    copySwapMemory0
 * Signature: (Ljava/lang/Object;JLjava/lang/Object;JJJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_Bits_copySwapMemory0
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
