/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_reflect_ReflectionFactory */

#ifndef _Included_sun_reflect_ReflectionFactory
#define _Included_sun_reflect_ReflectionFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_reflect_ReflectionFactory
 * Method:    newFieldAccessor
 * Signature: (Ljava/lang/reflect/Field;Z)Lsun/reflect/FieldAccessor;
 */
JNIEXPORT jobject JNICALL Java_sun_reflect_ReflectionFactory_newFieldAccessor
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     sun_reflect_ReflectionFactory
 * Method:    newMethodAccessor
 * Signature: (Ljava/lang/reflect/Method;)Lsun/reflect/MethodAccessor;
 */
JNIEXPORT jobject JNICALL Java_sun_reflect_ReflectionFactory_newMethodAccessor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_reflect_ReflectionFactory
 * Method:    newConstructorAccessor0
 * Signature: (Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;
 */
JNIEXPORT jobject JNICALL Java_sun_reflect_ReflectionFactory_newConstructorAccessor0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_reflect_ReflectionFactory
 * Method:    newConstructorAccessorForSerialization
 * Signature: (Ljava/lang/Class;Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;
 */
JNIEXPORT jobject JNICALL Java_sun_reflect_ReflectionFactory_newConstructorAccessorForSerialization
  (JNIEnv *, jclass, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
