/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_net_www_protocol_ikvmres_Handler */

#ifndef _Included_sun_net_www_protocol_ikvmres_Handler
#define _Included_sun_net_www_protocol_ikvmres_Handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_net_www_protocol_ikvmres_Handler
 * Method:    GenerateStub
 * Signature: (Ljava/lang/Class;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sun_net_www_protocol_ikvmres_Handler_GenerateStub
  (JNIEnv *, jclass, jclass);

/*
 * Class:     sun_net_www_protocol_ikvmres_Handler
 * Method:    ReadResourceFromAssemblyImpl
 * Signature: (Lcli/System/Reflection/Assembly;Ljava/lang/String;)Lcli/System/IO/Stream;
 */
JNIEXPORT jobject JNICALL Java_sun_net_www_protocol_ikvmres_Handler_ReadResourceFromAssemblyImpl
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     sun_net_www_protocol_ikvmres_Handler
 * Method:    LoadClassFromAssembly
 * Signature: (Lcli/System/Reflection/Assembly;Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_sun_net_www_protocol_ikvmres_Handler_LoadClassFromAssembly
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     sun_net_www_protocol_ikvmres_Handler
 * Method:    LoadAssembly
 * Signature: (Ljava/lang/String;)Lcli/System/Reflection/Assembly;
 */
JNIEXPORT jobject JNICALL Java_sun_net_www_protocol_ikvmres_Handler_LoadAssembly
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sun_net_www_protocol_ikvmres_Handler
 * Method:    GetGenericClassLoaderById
 * Signature: (I)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_sun_net_www_protocol_ikvmres_Handler_GetGenericClassLoaderById
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
