/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_internal_CallerID */

#ifndef _Included_ikvm_internal_CallerID
#define _Included_ikvm_internal_CallerID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_internal_CallerID
 * Method:    GetClass
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_internal_CallerID_GetClass
  (JNIEnv *, jobject);

/*
 * Class:     ikvm_internal_CallerID
 * Method:    GetClassLoader
 * Signature: ()Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_ikvm_internal_CallerID_GetClassLoader
  (JNIEnv *, jobject);

/*
 * Class:     ikvm_internal_CallerID
 * Method:    GetAssemblyClassLoader
 * Signature: (Lcli/System/Reflection/Assembly;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_ikvm_internal_CallerID_GetAssemblyClassLoader
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
