/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_Delegates_RunnableDelegate */

#ifndef _Included_ikvm_runtime_Delegates_RunnableDelegate
#define _Included_ikvm_runtime_Delegates_RunnableDelegate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_Delegates_RunnableDelegate
 * Method:    Invoke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ikvm_runtime_Delegates_00024RunnableDelegate_Invoke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
