/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_Startup */

#ifndef _Included_ikvm_runtime_Startup
#define _Included_ikvm_runtime_Startup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_Startup
 * Method:    addBootClassPathAssembly
 * Signature: (Lcli/System/Reflection/Assembly;)V
 */
JNIEXPORT void JNICALL Java_ikvm_runtime_Startup_addBootClassPathAssembly
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
