/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_Delegates_PrivilegedActionDelegate */

#ifndef _Included_ikvm_runtime_Delegates_PrivilegedActionDelegate
#define _Included_ikvm_runtime_Delegates_PrivilegedActionDelegate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_Delegates_PrivilegedActionDelegate
 * Method:    Invoke
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_Delegates_00024PrivilegedActionDelegate_Invoke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
