/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_Delegates_InvocationHandlerDelegate */

#ifndef _Included_ikvm_runtime_Delegates_InvocationHandlerDelegate
#define _Included_ikvm_runtime_Delegates_InvocationHandlerDelegate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_Delegates_InvocationHandlerDelegate
 * Method:    Invoke
 * Signature: (Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_Delegates_00024InvocationHandlerDelegate_Invoke
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
