/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_GenericClassLoader */

#ifndef _Included_ikvm_runtime_GenericClassLoader
#define _Included_ikvm_runtime_GenericClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_GenericClassLoader
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ikvm_runtime_GenericClassLoader_toString
  (JNIEnv *, jobject);

/*
 * Class:     ikvm_runtime_GenericClassLoader
 * Method:    getResources
 * Signature: (Ljava/lang/String;)Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_GenericClassLoader_getResources
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_GenericClassLoader
 * Method:    findResource
 * Signature: (Ljava/lang/String;)Ljava/net/URL;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_GenericClassLoader_findResource
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
