/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_Util */

#ifndef _Included_ikvm_runtime_Util
#define _Included_ikvm_runtime_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_Util
 * Method:    getClassFromObject
 * Signature: (Ljava/lang/Object;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_Util_getClassFromObject
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_runtime_Util
 * Method:    getClassFromTypeHandle
 * Signature: (Lcli/System/RuntimeTypeHandle;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_Util_getClassFromTypeHandle__Lcli_System_RuntimeTypeHandle_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_runtime_Util
 * Method:    getClassFromTypeHandle
 * Signature: (Lcli/System/RuntimeTypeHandle;I)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_Util_getClassFromTypeHandle__Lcli_System_RuntimeTypeHandle_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ikvm_runtime_Util
 * Method:    getFriendlyClassFromType
 * Signature: (Lcli/System/Type;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_Util_getFriendlyClassFromType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ikvm_runtime_Util
 * Method:    getInstanceTypeFromClass
 * Signature: (Ljava/lang/Class;)Lcli/System/Type;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_Util_getInstanceTypeFromClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     ikvm_runtime_Util
 * Method:    getRuntimeTypeFromClass
 * Signature: (Ljava/lang/Class;)Lcli/System/Type;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_Util_getRuntimeTypeFromClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     ikvm_runtime_Util
 * Method:    mapException
 * Signature: (Ljava/lang/Throwable;)Ljava/lang/Throwable;
 */
JNIEXPORT jthrowable JNICALL Java_ikvm_runtime_Util_mapException
  (JNIEnv *, jclass, jthrowable);

/*
 * Class:     ikvm_runtime_Util
 * Method:    unmapException
 * Signature: (Ljava/lang/Throwable;)Ljava/lang/Throwable;
 */
JNIEXPORT jthrowable JNICALL Java_ikvm_runtime_Util_unmapException
  (JNIEnv *, jclass, jthrowable);

#ifdef __cplusplus
}
#endif
#endif
