/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_runtime_AppDomainAssemblyClassLoader */

#ifndef _Included_ikvm_runtime_AppDomainAssemblyClassLoader
#define _Included_ikvm_runtime_AppDomainAssemblyClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_runtime_AppDomainAssemblyClassLoader
 * Method:    findClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_ikvm_runtime_AppDomainAssemblyClassLoader_findClass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AppDomainAssemblyClassLoader
 * Method:    findResource
 * Signature: (Ljava/lang/String;)Ljava/net/URL;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AppDomainAssemblyClassLoader_findResource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ikvm_runtime_AppDomainAssemblyClassLoader
 * Method:    concatResources
 * Signature: (Ljava/util/Enumeration;Ljava/lang/String;)Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_ikvm_runtime_AppDomainAssemblyClassLoader_concatResources
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
