/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ikvm_internal_AnnotationAttributeBase */

#ifndef _Included_ikvm_internal_AnnotationAttributeBase
#define _Included_ikvm_internal_AnnotationAttributeBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ikvm_internal_AnnotationAttributeBase
 * Method:    unescapeInvalidSurrogates
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ikvm_internal_AnnotationAttributeBase_unescapeInvalidSurrogates
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     ikvm_internal_AnnotationAttributeBase
 * Method:    newAnnotationInvocationHandler
 * Signature: (Ljava/lang/Class;Ljava/util/Map;)Ljava/lang/reflect/InvocationHandler;
 */
JNIEXPORT jobject JNICALL Java_ikvm_internal_AnnotationAttributeBase_newAnnotationInvocationHandler
  (JNIEnv *, jclass, jclass, jobject);

/*
 * Class:     ikvm_internal_AnnotationAttributeBase
 * Method:    newAnnotationTypeMismatchExceptionProxy
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ikvm_internal_AnnotationAttributeBase_newAnnotationTypeMismatchExceptionProxy
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
