/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_ClassStubZipEntry */

#ifndef _Included_java_util_zip_ClassStubZipEntry
#define _Included_java_util_zip_ClassStubZipEntry
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_zip_ClassStubZipEntry_STORED
#define java_util_zip_ClassStubZipEntry_STORED 0L
#undef java_util_zip_ClassStubZipEntry_DEFLATED
#define java_util_zip_ClassStubZipEntry_DEFLATED 8L
#undef java_util_zip_ClassStubZipEntry_DOSTIME_BEFORE_1980
#define java_util_zip_ClassStubZipEntry_DOSTIME_BEFORE_1980 2162688LL
#undef java_util_zip_ClassStubZipEntry_UPPER_DOSTIME_BOUND
#define java_util_zip_ClassStubZipEntry_UPPER_DOSTIME_BOUND 4036608000000LL
/*
 * Class:     java_util_zip_ClassStubZipEntry
 * Method:    expandIkvmClasses
 * Signature: (Ljava/util/zip/ZipFile;Ljava/util/LinkedHashMap;)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_ClassStubZipEntry_expandIkvmClasses
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
