/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_ThrowableHelper */

#ifndef _Included_java_lang_ThrowableHelper
#define _Included_java_lang_ThrowableHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_ThrowableHelper
 * Method:    getOurStackTrace
 * Signature: (Ljava/lang/Throwable;)[Ljava/lang/StackTraceElement;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_ThrowableHelper_getOurStackTrace
  (JNIEnv *, jclass, jthrowable);

#ifdef __cplusplus
}
#endif
#endif
