/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileDescriptor */

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_FileDescriptor
 * Method:    getFd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_io_FileDescriptor_getFd
  (JNIEnv *, jobject);

/*
 * Class:     java_io_FileDescriptor
 * Method:    setFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_setFd
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_io_FileDescriptor
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_java_io_FileDescriptor_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     java_io_FileDescriptor
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_io_FileDescriptor
 * Method:    standardStream
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_java_io_FileDescriptor_standardStream
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_io_FileDescriptor
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_sync
  (JNIEnv *, jobject);

/*
 * Class:     java_io_FileDescriptor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
