/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_management_OperatingSystemImpl */

#ifndef _Included_sun_management_OperatingSystemImpl
#define _Included_sun_management_OperatingSystemImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_management_OperatingSystemImpl_MAX_ATTEMPTS_NUMBER
#define sun_management_OperatingSystemImpl_MAX_ATTEMPTS_NUMBER 10L
/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getCommittedVirtualMemorySize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getCommittedVirtualMemorySize0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getFreePhysicalMemorySize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getFreePhysicalMemorySize0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getFreeSwapSpaceSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getFreeSwapSpaceSize0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getMaxFileDescriptorCount0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getMaxFileDescriptorCount0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getOpenFileDescriptorCount0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getOpenFileDescriptorCount0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getProcessCpuTime0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getProcessCpuTime0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getProcessCpuLoad0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_sun_management_OperatingSystemImpl_getProcessCpuLoad0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getSystemCpuLoad0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_sun_management_OperatingSystemImpl_getSystemCpuLoad0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getTotalPhysicalMemorySize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getTotalPhysicalMemorySize0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getTotalSwapSpaceSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getTotalSwapSpaceSize0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getSingleCpuLoad0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_sun_management_OperatingSystemImpl_getSingleCpuLoad0
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getHostConfiguredCpuCount0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_management_OperatingSystemImpl_getHostConfiguredCpuCount0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getHostOnlineCpuCount0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_management_OperatingSystemImpl_getHostOnlineCpuCount0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    getHostTotalCpuTicks0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_management_OperatingSystemImpl_getHostTotalCpuTicks0
  (JNIEnv *, jobject);

/*
 * Class:     sun_management_OperatingSystemImpl
 * Method:    initialize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_management_OperatingSystemImpl_initialize0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
