/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_misc_MiscHelper */

#ifndef _Included_sun_misc_MiscHelper
#define _Included_sun_misc_MiscHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_misc_MiscHelper
 * Method:    getAssemblyClassLoader
 * Signature: (Lcli/System/Reflection/Assembly;Ljava/lang/ClassLoader;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_sun_misc_MiscHelper_getAssemblyClassLoader
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
