#!/usr/bin/env python3
"""
Generate MobileGlues GL symbol lookup and prefix-override sources.

This script scans a MobileGlues archive and emits:

1) a C source file that exports `mobileglues_find_proc_address(const char*)`
   backed by a static symbol table
2) a C/C++ header with `#define` overrides that rewrite exported GL symbols
   from `glFoo` -> `mobileglues_glFoo` at compile time

`glX*` symbols are intentionally left unprefixed so LWJGL/JVM runtime lookups
for glX entry points continue to work.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
FUNCTION_TYPES = {"T", "W"}


def is_valid_ident(name: str) -> bool:
    return bool(IDENT_RE.match(name))


def find_nm(tool_hint: str | None) -> str:
    candidates = []
    if tool_hint:
        candidates.append(tool_hint)
    candidates.extend(["llvm-nm", "llvm-nm-20", "llvm-nm-19", "llvm-nm-18", "llvm-nm-17", "emnm", "nm"])

    for candidate in candidates:
        path = shutil.which(candidate)
        if path:
            return path

    raise FileNotFoundError("No nm-compatible tool found")


def read_exported_functions(archive: Path, nm_tool: str) -> list[str]:
    proc = subprocess.run(
        [nm_tool, "--defined-only", "--extern-only", str(archive)],
        check=True,
        capture_output=True,
        text=True,
    )

    symbols: set[str] = set()
    for raw in proc.stdout.splitlines():
        line = raw.strip()
        if not line or line.endswith(":"):
            continue

        parts = line.split()
        if len(parts) == 3:
            _, sym_type, sym_name = parts
        elif len(parts) == 2:
            sym_type, sym_name = parts
        else:
            continue

        if sym_type not in FUNCTION_TYPES:
            continue
        if not is_valid_ident(sym_name):
            continue

        symbols.add(sym_name)

    return sorted(symbols)


def is_lookup_symbol(name: str) -> bool:
    if name.startswith("mg_gl"):
        return True
    return len(name) > 2 and name.startswith("gl") and name[2].isupper()


def should_prefix(name: str) -> bool:
    if not (len(name) > 2 and name.startswith("gl") and name[2].isupper()):
        return False
    if name.startswith("glX"):
        return False
    return True


GL_PROTO_RE = re.compile(
    r"GLAPI\s+[^;{}]*?(?:APIENTRY|GLAPIENTRY)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(",
    re.MULTILINE,
)


def read_declared_gl_prototypes(source_root: Path) -> set[str]:
    headers = [
        source_root / "gl/gl.h",
        source_root / "gl/glext.h",
        source_root / "gl/glcorearb.h",
        source_root / "glx/lookup.h",
    ]

    declared: set[str] = set()
    for header in headers:
        if not header.is_file():
            continue
        text = header.read_text(encoding="utf-8", errors="ignore")
        declared.update(GL_PROTO_RE.findall(text))
    return declared


def escape_c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_lookup_c(entries: list[tuple[str, str]], c_path: Path, header_name: str) -> None:
    out: list[str] = []
    out.append("/* Auto-generated by gen-mobileglues-gl-symbols.py. */\n")
    out.append("#include <stddef.h>\n")
    out.append("#include <string.h>\n\n")
    out.append("#ifndef GL_GLEXT_PROTOTYPES\n#define GL_GLEXT_PROTOTYPES 1\n#endif\n")
    out.append("#ifndef GLCOREARB_PROTOTYPES\n#define GLCOREARB_PROTOTYPES 1\n#endif\n\n")
    out.append(f'#include "{header_name}"\n')
    out.append('#include "gl/gl.h"\n')
    out.append('#include "gl/glext.h"\n')
    out.append('#include "gl/glcorearb.h"\n')
    out.append('#include "glx/lookup.h"\n\n')
    out.append("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElementsBaseVertex_indirect(GLenum mode, GLsizei* counts, GLenum type, const void* const* indices, GLsizei primcount, const GLint* basevertex);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElementsBaseVertex_multiindirect(GLenum mode, GLsizei* counts, GLenum type, const void* const* indices, GLsizei primcount, const GLint* basevertex);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElementsBaseVertex_basevertex(GLenum mode, GLsizei* counts, GLenum type, const void* const* indices, GLsizei primcount, const GLint* basevertex);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElementsBaseVertex_drawelements(GLenum mode, GLsizei* counts, GLenum type, const void* const* indices, GLsizei primcount, const GLint* basevertex);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElementsBaseVertex_compute(GLenum mode, GLsizei* counts, GLenum type, const void* const* indices, GLsizei primcount, const GLint* basevertex);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElements_indirect(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei primcount);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElements_multiindirect(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei primcount);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElements_basevertex(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei primcount);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElements_drawelements(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei primcount);\n")
    out.append("GLAPI GLAPIENTRY void mg_glMultiDrawElements_compute(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei primcount);\n\n")
    out.append("typedef struct {\n")
    out.append("    const char* name;\n")
    out.append("    void* ptr;\n")
    out.append("} mobileglues_symbol_entry_t;\n\n")

    out.append("static const mobileglues_symbol_entry_t k_mobileglues_symbols[] = {\n")
    for lookup_name, target_name in entries:
        out.append(f'    {{"{escape_c_string(lookup_name)}", (void*){target_name}}},\n')
    out.append("    {NULL, NULL}\n")
    out.append("};\n\n")

    out.append("void* mobileglues_find_proc_address(const char* name) {\n")
    out.append("    size_t i;\n")
    out.append("\n")
    out.append("    if (!name) {\n")
    out.append("        return NULL;\n")
    out.append("    }\n")
    out.append("\n")
    out.append("    for (i = 0; k_mobileglues_symbols[i].name != NULL; ++i) {\n")
    out.append("        if (strcmp(k_mobileglues_symbols[i].name, name) == 0) {\n")
    out.append("            return k_mobileglues_symbols[i].ptr;\n")
    out.append("        }\n")
    out.append("    }\n")
    out.append("\n")
    out.append("    return NULL;\n")
    out.append("}\n\n")
    out.append("#ifdef __cplusplus\n}\n#endif\n")

    c_path.write_text("".join(out), encoding="utf-8")


def generate_prefix_header(renames: list[tuple[str, str]], header_path: Path) -> None:
    guard = "MOBILEGLUES_GL_PREFIX_OVERRIDES_H"
    out: list[str] = []
    out.append("/* Auto-generated by gen-mobileglues-gl-symbols.py. */\n")
    out.append(f"#ifndef {guard}\n")
    out.append(f"#define {guard}\n\n")

    for old_name, new_name in renames:
        out.append(f"#define {old_name} {new_name}\n")

    out.append(f"\n#endif /* {guard} */\n")
    header_path.write_text("".join(out), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MobileGlues GL symbol lookup source and rename map")
    parser.add_argument("--archive", required=True, help="Path to libmobileglues.a")
    parser.add_argument("--output-c", required=True, help="Output C source path")
    parser.add_argument("--output-header", required=True, help="Output C/C++ prefix override header path")
    parser.add_argument("--source-root", required=True, help="Path to MobileGlues-cpp source root")
    parser.add_argument("--nm", default=None, help="Optional nm binary to use")
    parser.add_argument("--prefix", default="mobileglues_", help="Prefix for renamed GL symbols")
    args = parser.parse_args()

    archive = Path(args.archive)
    output_c = Path(args.output_c)
    output_header = Path(args.output_header)
    source_root = Path(args.source_root)

    if not archive.is_file():
        print(f"error: archive not found: {archive}", file=sys.stderr)
        return 1

    try:
        nm_tool = find_nm(args.nm)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    all_symbols = read_exported_functions(archive, nm_tool)
    declared = read_declared_gl_prototypes(source_root)

    entries: list[tuple[str, str]] = []
    renames: list[tuple[str, str]] = []

    for symbol in all_symbols:
        if not is_lookup_symbol(symbol):
            continue

        if symbol.startswith("gl") and symbol not in declared:
            continue

        if should_prefix(symbol):
            prefixed = f"{args.prefix}{symbol}"
            entries.append((symbol, prefixed))
            renames.append((symbol, prefixed))
        else:
            entries.append((symbol, symbol))

    generate_prefix_header(renames, output_header)
    generate_lookup_c(entries, output_c, output_header.name)

    print(f"Using nm: {nm_tool}", file=sys.stderr)
    print(f"Declared prototypes: {len(declared)}", file=sys.stderr)
    print(f"Lookup entries: {len(entries)}", file=sys.stderr)
    print(f"Prefixed symbols: {len(renames)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
