name: IKVM WASM Build

env:
  EMSDK_VERSION: 3.1.56
  IKVM_REF: 8.14.0
  NATIVE_SDK_VERSION: "20251124.1"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-jtreg:
    name: Build OpenJDK Test Harness
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Checkout IKVM source
      uses: actions/checkout@v4
      with:
        repository: ikvmnet/ikvm
        path: ikvm
        ref: ${{ env.IKVM_REF }}
        submodules: recursive
    - name: Apply IKVM patch
      shell: bash
      run: |
        cd ikvm
        git apply $GITHUB_WORKSPACE/ikvm.patch
    - name: Cache OpenJDK Test Harness Build
      uses: actions/cache@v4
      with:
        path: ikvm/ext/jtreg/build
        key: jtreg-build--${{ runner.os }}--${{ hashFiles('ikvm/ext/jtreg/**') }}-8
    - name: Check OpenJDK Test Harness Build Stamp
      id: jtreg-build-stamp
      uses: andstor/file-existence-action@v3
      with:
        files: ikvm/ext/jtreg/build/stamp
    - name: Install Java
      run: |
        sudo apt-get update && \
        sudo apt-get install -y openjdk-8-jdk-headless && \
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
    - name: Build OpenJDK Test Harness
      if: steps.jtreg-build-stamp.outputs.files_exists != 'true'
      run: WGET_OPTS='-U Mozilla/5.0' bash make/build-all.sh $JAVA_HOME && touch build/stamp
      working-directory: ikvm/ext/jtreg
    - name: Package OpenJDK Test Harness
      run: zip -r /tmp/jtreg-build.zip build
      working-directory: ikvm/ext/jtreg
    - name: Upload OpenJDK Test Harness
      uses: actions/upload-artifact@v4
      with:
        name: jtreg-build
        path: /tmp/jtreg-build.zip

  build-ikvm:
    name: Build IKVM Managed Runtime
    needs:
    - build-jtreg
    timeout-minutes: 720
    runs-on: ubuntu-24.04
    env:
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Checkout IKVM source
      uses: actions/checkout@v4
      with:
        repository: ikvmnet/ikvm
        path: ikvm
        ref: ${{ env.IKVM_REF }}
        submodules: recursive
    - name: Apply IKVM patch
      shell: bash
      run: |
        cd ikvm
        git apply $GITHUB_WORKSPACE/ikvm.patch
    - name: Uninstall Packages
      run: |
        sudo apt-get remove --purge -y \
          temurin-\* \
          mono-complete \
          unixodbc-dev \
          nginx \
          php\* \
          postgresql\* \
          python3-dev python3-pip python3-venv \
          ruby-full \
          firefox \
          apache2 \
          ant && \
        sudo apt-get --purge autoremove -y && \
        sudo apt-get clean && \
        sudo rm -rf /usr/share/swift
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        android: false
        swap-storage: false
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8
    - name: Install Powershell
      run: |
        sudo apt-get update && \
        sudo apt-get install -y powershell
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install Mono
      run: |
        sudo apt-get update && \
        sudo apt-get install -y mono-runtime mono-devel
    - name: Install Java
      run: |
        sudo apt-get update && \
        sudo apt-get install -y openjdk-8-jdk-headless openjdk-21-jdk && \
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
    - name: Install LLVM and Clang
      run: |
        sudo apt-get update && \
        sudo apt-get install -y clang-20 llvm-20 && \
        echo "PATH=/usr/lib/llvm-18/bin:$PATH" >> $GITHUB_ENV
    - name: Install apple-codesign
      uses: baptiste0928/cargo-install@v3
      with:
        crate: apple-codesign
        version: latest
        locked: false
    - name: Set Version from IKVM_REF
      shell: bash
      run: |
        VERSION="${IKVM_REF}"
        echo "GitVersion_FullSemVer=${VERSION}" >> $GITHUB_ENV
        echo "GitVersion_SemVer=${VERSION}" >> $GITHUB_ENV
        echo "GitVersion_AssemblySemVer=${VERSION}.0" >> $GITHUB_ENV
        echo "GitVersion_AssemblySemFileVer=${VERSION}.0" >> $GITHUB_ENV
        echo "GitVersion_InformationalVersion=${VERSION}" >> $GITHUB_ENV
        echo "GitVersion_PreReleaseLabel=" >> $GITHUB_ENV
        echo "GitVersion_WeightedPreReleaseNumber=0" >> $GITHUB_ENV
    - name: Download JTReg Build
      uses: actions/download-artifact@v4
      with:
        name: jtreg-build
        path: /tmp
    - name: Restore JTReg Build
      run: mkdir -p ikvm/ext/jtreg && cd ikvm/ext/jtreg && unzip /tmp/jtreg-build.zip && rm /tmp/jtreg-build.zip
    - name: Download Native SDKs
      uses: robinraju/release-downloader@v1.9
      with:
        repository: ikvmnet/ikvm-native-sdk
        tag: ${{ env.NATIVE_SDK_VERSION }}
        fileName: "*.tar.gz"
        out-file-path: ikvm/ext/ikvm-native-sdk
        extract: true
    - name: Add NuGet Source (GitHub)
      shell: pwsh
      working-directory: ikvm
      run: dotnet nuget add source --username USERNAME --password $env:GITHUB_TOKEN --store-password-in-clear-text --name ikvm $env:GITHUB_REPOS
      env:
        GITHUB_REPOS: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: NuGet Restore
      run: dotnet restore IKVM.sln
      working-directory: ikvm
    - name: Build Artifacts
      timeout-minutes: 240
      working-directory: ikvm
      run: |
        dotnet msbuild /m /bl \
          /p:Configuration="Release" \
          /p:Platform="Any CPU" \
          /p:PreReleaseLabel=${GitVersion_PreReleaseLabel} \
          /p:PreReleaseNumber=${GitVersion_WeightedPreReleaseNumber} \
          /p:Version=${GitVersion_FullSemVer} \
          /p:AssemblyVersion=${GitVersion_AssemblySemVer} \
          /p:InformationalVersion=${GitVersion_InformationalVersion} \
          /p:FileVersion=${GitVersion_AssemblySemFileVer} \
          /p:PackageVersion=${GitVersion_FullSemVer} \
          /p:RepositoryUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" \
          /p:PackageProjectUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
          /p:BuildInParallel=true \
          /p:CreateHardLinksForAdditionalFilesIfPossible=true \
          /p:CreateHardLinksForCopyAdditionalFilesIfPossible=true \
          /p:CreateHardLinksForCopyFilesToOutputDirectoryIfPossible=true \
          /p:CreateHardLinksForCopyLocalIfPossible=true \
          /p:CreateHardLinksForPublishFilesIfPossible=true \
          /p:ContinuousIntegrationBuild=true \
          /p:ClangToolExe="/usr/bin/clang-20" \
          /p:LlvmArToolExe="/usr/bin/llvm-ar-20" \
          IKVM.dist.msbuildproj
    - name: Upload MSBuild Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: msbuild.binlog
        path: ikvm/msbuild.binlog
    - name: Package Managed DLLs
      shell: bash
      run: |
        mkdir -p out/managed

        BYTECODE_DLL=$(find $NUGET_PACKAGES/ikvm.bytecode -name "IKVM.ByteCode.dll" -path "*/net8.0/*" | head -1)

        cp ikvm/src/IKVM.Runtime/bin/Release/net8.0/IKVM.Runtime.dll out/managed/
        cp ikvm/src/IKVM.CoreLib/bin/Release/net8.0/IKVM.CoreLib.dll out/managed/
        cp ikvm/src/IKVM.Java/bin/Release/net8.0/IKVM.Java.dll out/managed/
        cp "$BYTECODE_DLL" out/managed/

        tar czvf /tmp/managed-dlls.tar.gz -C out/managed .
    - name: Upload Managed DLLs
      uses: actions/upload-artifact@v4
      with:
        name: managed-dlls
        path: /tmp/managed-dlls.tar.gz

  build-wasm-native:
    name: Build WASM Native (pthread=${{ matrix.pthread_enabled }})
    strategy:
      matrix:
        pthread_enabled: [true, false]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Checkout IKVM source
      uses: actions/checkout@v4
      with:
        repository: ikvmnet/ikvm
        path: ikvm
        ref: ${{ env.IKVM_REF }}
        submodules: recursive
    - name: Apply IKVM patch
      shell: bash
      run: |
        cd ikvm
        git apply $GITHUB_WORKSPACE/ikvm.patch
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EMSDK_VERSION }}
    - name: Build WASM native artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p out/native/tmp

        PREFIX=""
        PTHREAD_FLAGS=()

        if [ "${{ matrix.pthread_enabled }}" = "false" ]; then
          PREFIX="ST-"
        else
          PTHREAD_FLAGS=( -pthread )
        fi

        LIBJVM_SRC="ikvm/src/libjvm"
        LIBIKVM_SRC="ikvm/src/libikvm"
        OPENJDK_DIR="ikvm/ext/openjdk"

        COMMON_DEFS=( -DTARGET_ARCH_x86 -DTARGET_OS_FAMILY_linux -DLINUX -D__int64='long long' )
        COMMON_INCLUDES=(
          -I"$LIBJVM_SRC"
          -I"$OPENJDK_DIR/hotspot/src/share/vm"
          -I"$OPENJDK_DIR/hotspot/src/share/vm/prims"
          -I"$OPENJDK_DIR/hotspot/src/cpu/x86/vm"
          -I"$OPENJDK_DIR/hotspot/src/os/linux/vm"
          -I"$OPENJDK_DIR/jdk/src/share/javavm/export"
          -I"$OPENJDK_DIR/jdk/src/solaris/javavm/export"
          -I"$OPENJDK_DIR/jdk/src/linux/javavm/export"
        )

        emcc -O2 -fPIC -fdeclspec "${PTHREAD_FLAGS[@]}" -c "$LIBJVM_SRC/jni.c" -o out/native/tmp/jni.o "${COMMON_DEFS[@]}" "${COMMON_INCLUDES[@]}"
        emcc -O2 -fPIC -fdeclspec "${PTHREAD_FLAGS[@]}" -c "$LIBJVM_SRC/jni_vargs.c" -o out/native/tmp/jni_vargs.o "${COMMON_DEFS[@]}" "${COMMON_INCLUDES[@]}"
        em++ -O2 -fPIC -std=c++11 -Wno-error -fdeclspec "${PTHREAD_FLAGS[@]}" -c "$LIBJVM_SRC/jvm.cpp" -o out/native/tmp/jvm.o "${COMMON_DEFS[@]}" "${COMMON_INCLUDES[@]}"
        emar rcs "out/native/${PREFIX}libjvm.a" out/native/tmp/jni.o out/native/tmp/jni_vargs.o out/native/tmp/jvm.o

        emcc -O2 -fPIC -DLINUX "${PTHREAD_FLAGS[@]}" -c "$LIBIKVM_SRC/dl.c" -o out/native/tmp/dl.o
        emcc -O2 -fPIC -DLINUX "${PTHREAD_FLAGS[@]}" -c "$LIBIKVM_SRC/sig.c" -o out/native/tmp/sig.o
        emar rcs "out/native/${PREFIX}libikvm.a" out/native/tmp/dl.o out/native/tmp/sig.o
    - name: Upload WASM native artifacts (pthread=${{ matrix.pthread_enabled }})
      uses: actions/upload-artifact@v4
      with:
        name: wasm-native-pthread-${{ matrix.pthread_enabled }}
        path: out/native/*.a

  release:
    runs-on: ubuntu-latest
    needs: [build-ikvm, build-wasm-native]
    permissions:
      contents: write
    name: Create Release
    steps:
    - name: Generate release id
      run: echo RELEASE_NAME=$(uuidgen) >> $GITHUB_ENV

    - name: Download managed DLLs
      uses: actions/download-artifact@v4
      with:
        name: managed-dlls
        path: /tmp/managed

    - name: Restore managed DLLs
      run: |
        mkdir -p managed
        tar xzvf /tmp/managed/managed-dlls.tar.gz -C managed

    - name: Download WASM native artifacts (pthread=true)
      uses: actions/download-artifact@v4
      with:
        name: wasm-native-pthread-true
        path: native/

    - name: Download WASM native artifacts (pthread=false)
      uses: actions/download-artifact@v4
      with:
        name: wasm-native-pthread-false
        path: native/

    - name: Bundle artifacts
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p release

        # Bundle MT (pthread) version
        zip -j "release/ikvm-wasm-bundle.zip" \
          managed/IKVM.Runtime.dll \
          managed/IKVM.CoreLib.dll \
          managed/IKVM.Java.dll \
          managed/IKVM.ByteCode.dll \
          native/libjvm.a \
          native/libikvm.a

        # Bundle ST (no pthread) version
        zip -j "release/ikvm-wasm-ST-bundle.zip" \
          managed/IKVM.Runtime.dll \
          managed/IKVM.CoreLib.dll \
          managed/IKVM.Java.dll \
          managed/IKVM.ByteCode.dll \
          native/ST-libjvm.a \
          native/ST-libikvm.a

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: "IKVM WASM ${{ env.RELEASE_NAME }}"
        body: "These are the IKVM libs built for WASM (Emscripten)"
        commit: ${{ github.ref_name }}
        tag: ${{ env.RELEASE_NAME }}
        removeArtifacts: true
        artifacts: "release/*"
        token: ${{ secrets.GITHUB_TOKEN }}
